// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SmartAdmin.WebUI.Models;
using System;
using System.Collections.Generic;

namespace SmartAdmin.WebUI.ViewModels
{
    public partial class OherBookingViewModel
    {
        public long Id { get; set; }
        public DateTime? BookingDate { get; set; }
        public TimeSpan? BookingTime { get; set; }
        public string BookingDateString { get; set; }
        public string BookingTimeString { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CategoryId { get; set; }
        public string Message { get; set; }
        public string AppointMentType { get; set; }

        public virtual AppoinmentCategory Category { get; set; }
        public virtual User User { get; set; }
    }
}