// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    public partial class AnswerOption
    {
        [Key]
        public long OptionId { get; set; }
        public long? QuestionId { get; set; }
        [StringLength(4000)]
        public string OptionTitle { get; set; }
        [StringLength(4000)]
        public string OptionDesc { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public long? UpdatedBy { get; set; }
        public double? OptionSeq { get; set; }

        [ForeignKey(nameof(QuestionId))]
        [InverseProperty("AnswerOptions")]
        public virtual Question Question { get; set; }
    }
}