// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("AppointmentDocument")]
    public partial class AppointmentDocument
    {
        [Key]
        public long Id { get; set; }
        public long? CreatedBy { get; set; }
        public long? AppointmentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UploadedOn { get; set; }
        [StringLength(200)]
        public string FileName { get; set; }

        [ForeignKey(nameof(AppointmentId))]
        [InverseProperty("AppointmentDocuments")]
        public virtual Appointment Appointment { get; set; }
    }
}