// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    public partial class Appointment
    {
        public Appointment()
        {
            AppointmentDocuments = new HashSet<AppointmentDocument>();
        }

        [Key]
        public long Id { get; set; }
        public long? ClientId { get; set; }
        public int? CategoryId { get; set; }
        public Guid? UserId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AppointmentDate { get; set; }
        public TimeSpan? AppointMentFrom { get; set; }
        public TimeSpan? AppointMentTo { get; set; }
        public long? AppointmentStatus { get; set; }
        [StringLength(400)]
        public string AppointmentRemark { get; set; }
        [StringLength(50)]
        public string AppointMentType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public long? UpdatedBy { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(AppoinmentCategory.Appointments))]
        public virtual AppoinmentCategory Category { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Appointments")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(AppointmentDocument.Appointment))]
        public virtual ICollection<AppointmentDocument> AppointmentDocuments { get; set; }
    }
}