// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("AppoinmentCategory")]
    public partial class AppoinmentCategory
    {
        public AppoinmentCategory()
        {
            Appointments = new HashSet<Appointment>();
            Availabilities = new HashSet<Availability>();
            OherBookings = new HashSet<OherBooking>();
        }

        [Key]
        public int Id { get; set; }
        public int? SlotDuration { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public long? ClientId { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
        public long? UpdatedBy { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty("AppoinmentCategories")]
        public virtual Client Client { get; set; }
        [InverseProperty(nameof(Appointment.Category))]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [InverseProperty(nameof(Availability.Category))]
        public virtual ICollection<Availability> Availabilities { get; set; }
        [InverseProperty(nameof(OherBooking.Category))]
        public virtual ICollection<OherBooking> OherBookings { get; set; }
    }
}