// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("Availability")]
    public partial class Availability
    {
        [Key]
        public long Id { get; set; }
        public int? CategoryId { get; set; }
        public bool? IsBooked { get; set; }
        public int? ClientId { get; set; }
        public long? TimingId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public bool? IsAvailable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(AppoinmentCategory.Availabilities))]
        public virtual AppoinmentCategory Category { get; set; }
        [ForeignKey(nameof(TimingId))]
        [InverseProperty("Availabilities")]
        public virtual Timing Timing { get; set; }
    }
}