// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("BroadCast")]
    public partial class BroadCast
    {
        [Key]
        public int Id { get; set; }
        public long? ClientId { get; set; }
        public string BroadCastUrl { get; set; }
        [StringLength(50)]
        public string BroadCastType { get; set; }
        public string BroadCastTitle { get; set; }
        public string BroadCastDescription { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty("BroadCasts")]
        public virtual Client Client { get; set; }
    }
}