// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("Client")]
    public partial class Client
    {
        public Client()
        {
            AppoinmentCategories = new HashSet<AppoinmentCategory>();
            BroadCasts = new HashSet<BroadCast>();
            ContentManagers = new HashSet<ContentManager>();
            EmployeeMasters = new HashSet<EmployeeMaster>();
            Settings = new HashSet<Setting>();
            Timings = new HashSet<Timing>();
            Users = new HashSet<User>();
        }

        [Key]
        public long Id { get; set; }
        [StringLength(100)]
        public string GroupCode { get; set; }
        [StringLength(200)]
        public string ClientName { get; set; }
        public string ClientOverView { get; set; }
        public string ClientLogo { get; set; }
        [StringLength(400)]
        public string WebSiteUrl { get; set; }
        [StringLength(200)]
        public string ContactPerson { get; set; }
        [StringLength(200)]
        public string ContactNumber { get; set; }
        [StringLength(200)]
        public string ContactEmail { get; set; }
        [StringLength(4000)]
        public string Address { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(4000)]
        public string Col1 { get; set; }
        [StringLength(4000)]
        public string Col2 { get; set; }
        [StringLength(4000)]
        public string Col3 { get; set; }
        [StringLength(4000)]
        public string Col4 { get; set; }
        [StringLength(4000)]
        public string Col5 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public long? UpdatedBy { get; set; }

        [InverseProperty(nameof(AppoinmentCategory.Client))]
        public virtual ICollection<AppoinmentCategory> AppoinmentCategories { get; set; }
        [InverseProperty(nameof(BroadCast.Client))]
        public virtual ICollection<BroadCast> BroadCasts { get; set; }
        [InverseProperty(nameof(ContentManager.Client))]
        public virtual ICollection<ContentManager> ContentManagers { get; set; }
        [InverseProperty(nameof(EmployeeMaster.Client))]
        public virtual ICollection<EmployeeMaster> EmployeeMasters { get; set; }
        [InverseProperty(nameof(Setting.Client))]
        public virtual ICollection<Setting> Settings { get; set; }
        [InverseProperty(nameof(Timing.Client))]
        public virtual ICollection<Timing> Timings { get; set; }
        [InverseProperty(nameof(User.Client))]
        public virtual ICollection<User> Users { get; set; }
    }
}