// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("EmployeeMaster")]
    public partial class EmployeeMaster
    {
        [Key]
        public long Id { get; set; }
        public long? ClientId { get; set; }
        [StringLength(50)]
        public string EmployeeCode { get; set; }
        [StringLength(200)]
        public string FirstName { get; set; }
        [StringLength(200)]
        public string LastName { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [StringLength(50)]
        public string DependantType { get; set; }
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        public int? Age { get; set; }
        public bool? IsDependent { get; set; }
        public bool? IsCovered { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CoverStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CoverEndDate { get; set; }
        public long? PlanId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public long? CreatedBy { get; set; }
        public long? ModifiedBy { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty("EmployeeMasters")]
        public virtual Client Client { get; set; }
    }
}