// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("OherBooking")]
    public partial class OherBooking
    {
        [Key]
        public long Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BookingDate { get; set; }
        public TimeSpan? BookingTime { get; set; }
        public Guid? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public int? CategoryId { get; set; }
        public string Message { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(AppoinmentCategory.OherBookings))]
        public virtual AppoinmentCategory Category { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("OherBookings")]
        public virtual User User { get; set; }
    }
}