// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    public partial class Question
    {
        public Question()
        {
            AnswerOptions = new HashSet<AnswerOption>();
        }

        [Key]
        public long QuestionId { get; set; }
        [StringLength(4000)]
        public string QuestionTitle { get; set; }
        [StringLength(4000)]
        public string QuestionDesc { get; set; }
        public bool? IsMandatory { get; set; }
        [StringLength(400)]
        public string AnswerType { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public long? UpdatedBy { get; set; }
        [StringLength(400)]
        public string AnswerDataType { get; set; }
        public double? Sequence { get; set; }
        [StringLength(4000)]
        public string RefCol { get; set; }
        public long? PreviousOptionId { get; set; }

        [InverseProperty(nameof(AnswerOption.Question))]
        public virtual ICollection<AnswerOption> AnswerOptions { get; set; }
    }
}