// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    [Table("Setting")]
    public partial class Setting
    {
        [Key]
        public long Id { get; set; }
        public long? ClientId { get; set; }
        [StringLength(200)]
        public string SettingType { get; set; }
        [StringLength(200)]
        public string SettingName { get; set; }
        [StringLength(400)]
        public string SettingValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public long? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public long? UpdatedBy { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty("Settings")]
        public virtual Client Client { get; set; }
    }
}