// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartAdmin.WebUI.Models
{
    public partial class Timing
    {
        public Timing()
        {
            Availabilities = new HashSet<Availability>();
        }

        [Key]
        public long Id { get; set; }
        public long? ClientId { get; set; }
        [StringLength(50)]
        public string Day { get; set; }
        public TimeSpan? MorningStart { get; set; }
        public TimeSpan? MorningEnd { get; set; }
        public TimeSpan? EveningStart { get; set; }
        public TimeSpan? EveningEnd { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(ClientId))]
        [InverseProperty("Timings")]
        public virtual Client Client { get; set; }
        [InverseProperty(nameof(Availability.Timing))]
        public virtual ICollection<Availability> Availabilities { get; set; }
    }
}